version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: mocha-eslint
    versions:
    - "> 4.1.0"
  - dependency-name: ember-cli
    versions:
    - 3.23.0
    - 3.24.0
